const categorias = [
  { id: "Eletro", nome: "Eletrodomésticos" },
  { id: "Utensilhos", nome: "Cozinha" },
  { id: "Banheiro", nome: "Itens para Banheiro" },
  { id: "Vale", nome: "Vale Presente" },
  { id: "Quarto", nome: "Quarto" },
  { id: "SalaEstar", nome: "Sala de Estar" },
  { id: "Noivos", nome: "Vida dos Noivos" },
  { id: "Noivo", nome: "Alegria do Noivo TI" },
  { id: "Noiva", nome: "Alegria da Noiva Designer" }
];

//Eletro
const gifts = [
  {
    id: 1,
    category: "Eletro",
    name: "Geladeira/Refrigerador Brastemp Frost Free Duplex Prata 463L BRM55FK",
    price: 3699,
    image: 'assets/Geladeira.jpg',
    pix: "PIX_CODIGO_AQUI",
    link: "https://www.magazineluiza.com.br/geladeira-refrigerador-brastemp-frost-free-duplex-prata-463l-brm55fk/p/238402400/ed/refr/?partner_id=64853&utm_source=pdp_desk&utm_medium=share"
  },
  {
    id: 2,
    category: "Eletro",
    name: "Micro-Ondas Electrolux Prata com Painel Integrado 31L (MI41S)",
    price: 749,
  image: "assets/Microondas.jpg",
    pix: "PIX_CODIGO_AQUI",
    link: "https://site.fastshop.com.br/micro-ondas-electrolux-prata-com-painel-integrado-31l--mi41s--exmi41s_prd/p?idsku=12601&utm_source=bing&utm_medium=cpc&utm_campaign=%5Bli%5D_lb_%5Bst%5D_comercial_%5Bch%5D_1p_%5Bpl%5D_bing_%5Bty%5D_shop&utm_term=&utm_placement=o&msclkid=8b66da23f62a1d0c1c1db348f52b5466"
  },
  {
    id: 3,
    category: "Eletro",
    name: "Fogão 4 bocas Electrolux Prata Efficient com Mesa de Vidro, Tripla Chama e VaporBake",
    price: 1699,
    image: "assets/Fogão.jpg",
    pix: "PIX_CODIGO_AQUI",
    link: "https://loja.electrolux.com.br/fogao-4-bocas-electrolux-prata-efficient-com-mesa-de-vidro-perfectcook-e-vaporbake--fe4gs-/p?idsku=310120614&msclkid=8715e428882110340e338d438b8d31dc&utm_source=bing&utm_medium=cpc&utm_campaign=%5BVitrio%5D%20PLA%20%7C%20USC%20%7C%20Top%20Produtos&utm_term=2333713430298929&utm_content=Top%20Produtos  "
  },
  {
    id: 4,
    category: "Eletro",
    name: "Samsung Lava e Seca Digital Inverter Ecobubble™ WD10M Branca 10.1kg 220V",
    price: 3299,
    image:"assets/Maquina.jpg",
    pix: "",
    link: "https://a.co/d/1HJRsDg",
  },
  {
    id: 5,
    category: "Eletro",
    name: "Smart TV QLED 4K Samsung 55'' Q60B",
    price: 1597,
    image: "assets/Tv.jpg",
    pix: "",
    link: "https://www.magazineluiza.com.br/smart-tv-43-philips-full-hd-dled-43pfg6918-78-60hz-google-tv-quad-core-google-assistente-3-hdm/p/240247300/et/elit/?partner_id=64853&utm_source=pdp_desk&utm_medium=share"
  },
  {
    id: 6,
    category: "Eletro",
    name: "Aspirador de Pó Vertical Britânia Filtro HEPA 1250W BAS1295P Preto",
    price: 151.91,
    image: "assets/Aspirador.jpg",
    pix: "",
    link: "https://www.magazineluiza.com.br/aspirador-de-po-vertical-britania-filtro-hepa-1250w-bas1295p-preto/p/237879000/ep/apdv/?partner_id=64853&utm_source=pdp_desk&utm_medium=share",
  },
  {
    id: 7,
    category: "Eletro",
    name: "Purificador Refrigerado New E-DUE Equilibrium Grafite Full Range",
    price: 424.71,
    image: "assets/Purificador.jpg",
    pix: "",
    link: "https://www.amazon.com.br/PURIFICADOR-REFRIGERADO-EQUILIBRIUM-GRAFITE-RANGE/dp/B0BYT8HSBJ/ref=sr_1_6?adgrpid=123411265661&dib=eyJ2IjoiMSJ9.RxDNuUNW_L8mcBHpA8xaStVnIi-MNEdom_liiTWOr-a5i33lfjQMUj1pgJ7w_lXZd8Pw3gfUULJFFBI4F1ODhBtzClIsYKarJcvcwLYzKQqg-UBMFzvd2OXL27HWajwWNQ43K6ERUxKNcD2-dEUz96hvMVFHjxbYZ-gElHRc6dXlI8nKNlo14CA_4gR5Ajtv2Tmb-kh226U_zxXHOfTNlZrjkIef5btlXxIousNnS4nmIpLyA_0GKAS-_TgPDpOV8oirEWIvAA7vHhtFcQ9YlUDK-rpiOJN-0K7Uvke_xAQ.iMbeb4oKIuHrXkixGKMsZv1TtdeChjGzjEsM-xY_Qdk&dib_tag=se&hvadid=595999548395&hvdev=c&hvlocphy=9102133&hvnetw=g&hvqmt=e&hvrand=7265428901904683445&hvtargid=kwd-323881866840&hydadcr=10637_13510007&keywords=purificador%2Bde%2Bagua%2Bgelada&mcid=bbe676adb5953401b07008193d9b3089&qid=1768688707&sr=8-6&ufe=app_do%3Aamzn1.fos.e05b01e0-91a7-477e-a514-15a32325a6d6&th=1",
  },
  {
    id: 8,
    category: "Eletro",
    name: "Ferro de Passar Seco e vapor base ceramica vapor vertical extra alta capacidade 1500W ESI50 127v", 
    price: 186,
    image: "assets/Ferro.jpg",
    pix: "",
    link: "https://www.amazon.com.br/Electrolux-antiaderente-ceramica-Glissium-capacidade/dp/B0CCJXMYSR/ref=sr_1_16?crid=SE5IBE62Z72X&dib=eyJ2IjoiMSJ9.xpGHdmyIOrx-5aDhCtCX34jCQQyp0lhblu_R9NRAzSaL1ZZvu7yxr4xjVeLrANtAMKH5bIZFdl7sM-KYoAt7EXSFWTQB3D7Ba0ZmEsIqyW1tBdBqa8zCSt-5DLD2wgcxPkULx0s2Kfboh5n5n3xIi2FFtNrLLXB-lQVNIlQ3BdmtFPhE8JS6U2IvkKqZeNjRokIieoNo58dwsdwgzqLbRX8pIUYs2TPGF9Bvj618Ki48W0j9g_RO-SDlIpcUmNwGgVt97cFTjHHTib9Q4QHohXkSyGYgLU_GQ7R1F0mXF4Q.JLtwNcO_iQ7lFHsz2RnaPysPlE_sLFFYw2IcAHVGg6E&dib_tag=se&keywords=ferro%2Bde%2Bpassar%2Broupa%2Bvapor%2Bceramica&qid=1768689242&sprefix=ferro%2Bde%2Bpassar%2Broupa%2Bvapor%2B%2Caps%2C225&sr=8-16&ufe=app_do%3Aamzn1.fos.db68964d-7c0e-4bb2-a95c-e5cb9e32eb12&th=1",
  } ,
  { 
    id: 9,
    category: "Eletro",
    name: "MONDIAL Ventilador de Mesa 110V, 30cm, 6 pás, Super Power - VSP-30-B",
    price: 119.90,
    image: "assets/Ventilador.jpg",
    pix: "",
    link: "https://a.co/d/dYAYOXS",

  },
  {
    id: 10,
    category: "Eletro",
    name: "Ar Condicionado Split Elgin Eco Inverter Ii Wi-fi 12000 Btu/ Cor Branco",
    price: 2119,
    image: "assets/Ar.jpg",
    pix: "",
    link: "https://www.mercadolivre.com.br/ar-condicionado-split-elgin-eco-inverter-ii-wi-fi-12000-btu-cor-branco/p/MLB55577033?pdp_filters=item_id%3AMLB6167046088#origin%3Dshare%26sid%3Dshare%26wid%3DMLB6167046088",
  } ,
  {
    id: 11,
    category: "Eletro",
    name: "Nescafé Dolce Gusto Arno Genio S Basic Branca Dgs1 Cor Branco",
    price: 421.90,
    image: "assets/Cafeteira.jpg",
    pix: "",
    link: "https://www.mercadolivre.com.br/nescafe-dolce-gusto-arno-genio-s-basic-branca-dgs1-cor-branco/p/MLB44389497?pdp_filters=item_id%3AMLB6105980776#origin%3Dshare%26sid%3Dshare%26wid%3DMLB6105980776",
  },
  {
    id: 12,
    category: "Eletro",
    name: "Sanduicheira Fast Grill e Sandwich Mondial S-12 750W - Preta - 110V",
    price: 89,
    image: "assets/Sanduiche.jpg",
    pix: "",
    link: "https://www.casasbahia.com.br/sanduicheira-fast-grill-e-sandwich-mondial-s-12-750w-preta/p/3230329?utm_medium=cpc&utm_source=GP_PLA&IdSku=3230329&idLojista=10037&tipoLojista=1P&gclsrc=aw.ds&&utm_campaign=cb_b2c_gg_shopping_core_elpo_geral&gad_source=1&gad_campaignid=22439146548&gbraid=0AAAAADtAamgdsRmjDDltTfaRZHbfxQohR&gclid=Cj0KCQiAg63LBhDtARIsAJygHZ6CM4DlpBwzqEGNmmxGzaKPyEml5OIGCWF8lUHliiMy7RGFp8O1hmQaAgNyEALw_wcB",
  },
  {
    id: 13,
    category: "Eletro",
    name: "Liquidificador Mondial L-99 com Filtro - Copo Cristal, 3 Velocidades + Pulsar, 550W, Branco",
    price: 94.05,
    image: "assets/Liquidificador.jpg",
    pix: "",
    link: "https://www.magazineluiza.com.br/liquidificador-mondial-l-99-com-filtro-copo-cristal-3-velocidades-pulsar-550w-branco/p/fj8471j53d/ep/liqu/?seller_id=magazineluiza",
  },
  // Utensilhos
  {
  id: 14,
  category: "Utensilhos",
  name: "", 
  price: 0,
  image: "",
  pix: "",
  link: "",
  } ,
  {
    id: 15,
    category: "Utensilhos",
    name: "", 
    price: 0,
    image: "",
    pix: "",
    link: "",
  } ,
  {
    id: 16,
    category: "Utensilhos",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 17,
    category: "Utensilhos",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 18,
    category: "Utensilhos",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 19,
    category: "Utensilhos",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  //Banheiro
  {
    id: 20,
    category: "Banheiro",
    name: "Jogo Toalhas Groh Marselha 100% Algodão Kit 4 Banho e Rosto",
    price: 58.49,
    image: "assets/Toalha.jpg",
    pix: "",
    link: "https://www.mercadolivre.com.br/jogo-toalhas-groh-marselha-100-algodo-kit-4-banho-e-rosto/p/MLB29353656#reviews",
  }, 
  {
    id: 21,
    category: "Banheiro",
    name: "Kit 04 Tapete Banheiro 38x58 Antiderrapante Bolinha Macarrão lavabo casa felpudo box absorvente água",
    price: 58.90,
    image: "assets/Tapete.jpg",
    pix: "",
    link: "https://www.magazineluiza.com.br/kit-04-tapete-banheiro-38x58-antiderrapante-bolinha-macarrao-lavabo-casa-felpudo-box-absorvente-agua-marias-enxoval/p/bhkb1ghf55/cm/ctap/",
  },
  {
    id: 22,
    category: "Banheiro",
    name: "Kit Lavabo com Bandeja – Kit Banheiro Saboneteira e Conjunto para Banheiro",
    price: 54.90,
    image: "assets/Saboneteira.jpg",
    pix: "",
    link: "https://www.amazon.com.br/Kit-Lavabo-com-Bandeja-Saboneteira/dp/B0DSGPTR1N/ref=asc_df_B0DSGPTR1N?tag=brbngshpdsk-20&linkCode=df0&hvadid=77447066850023&hvnetw=o&hvqmt=e&hvbmt=be&hvdev=c&hvlocint=&hvlocphy=147100&hvtargid=pla-4581046495425142&msclkid=840c431314a6167912872a7f417c370c&th=1 ",
  },
  {    
    id: 23,
    category: "Banheiro",
    name: "Kit 2 Porta Shampoo Reto De Vidro Quadrado Luxo Quadrus",
    price: 57.99,
    image: "assets/Porta Shampoo.jpg",
    pix: "",
    link: "https://www.mercadolivre.com.br/kit-2-porta-shampoo-reto-de-vidro-quadrado-luxo-quadrus/p/MLB53633882#reviews",
  },
  //Sala de Estar
  {
    id: 24,
    category: "SalaEstar",
    name: "Sofá Cama Retrátil E Reclinável Aurora Gelo Chwt Cor Gelo",
    price: 2378.93,
    image: "assets/Sofa.jpg",
    pix: "",
    link: "https://www.mercadolivre.com.br/sofa-cama-retratil-e-reclinavel-aurora-gelo-chwt-cor-gelo/p/MLB38227886?product_trigger_id=MLB37998612&picker=true&quantity=1#&gid=1&pid=2",
  },
  {
    id: 25,
    category: "SalaEstar",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 26,
    category: "SalaEstar",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 27,
    category: "SalaEstar",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 28,
    category: "SalaEstar",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 29,
    category: "SalaEstar",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  //Vale Presente
  {
    id: 30,
    category: "Vale",
    name: "Vale Presente R$ 200,00",
    price: 200,
    image: "",
    pix: "",

  },
  {
    id: 31,
    category: "Vale",
    name: "Vale Presente R$ 500,00",
    price: 500,
    image: "",
    pix: "",

  }, 
  {
    id: 32,
    category: "Vale",
    name: "Vale Presente R$ 1.000,00",
    price: 1000,
    image: "",
    pix: "",
  },
  {
    id: 33,
    category: "Vale",
    name: "Vale Presente R$ 1.500,00",
    price: 1500,
    image: "",
    pix: "",
  },
  {
    id: 34,
    category: "Vale",
    name: "Vale Presente R$ 2.000,00",
    price: 2000,
    image: "",
    pix: "",
  },
  {
    id: 35,
    category: "Vale",
    name: "Vale Presente R$ 2.500,00",
    price: 2500,
    image: "",
    pix: "",
  },
  {
    id: 36,
    category: "Vale",
    name: "Vale Presente R$ 3.000,00",
    price: 3000,
    image: "",
    pix: "",
  },
  //Quarto
  {
    id: 37,
    category: "Quarto",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 38,
    category: "Quarto",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 39,
    category: "Quarto",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {    id: 40,
    category: "Quarto",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 41,
    category: "Quarto",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 42,
    category: "Quarto",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 43,
    category: "Quarto",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  //Vida Noivos
  {
    id: 44,
    category: "Noivos",
    name: "Nos Ajude a Pagar a Lua de Mel!",
    price: 459,
    image: "",  
    pix: "",
  },
  {
    id: 45,
    category: "Noivos",
    name: "Nos Ajude a Pagar os Boletos (São muitos)",
    price: 250,
    image: "",
    pix: "",
  },
  {
    id: 46,
    category: "Noivos",
    name: "Noivo com o Cabelo Cortado Garantido!",
    price: 120,
    image: "",
    pix: "",
  },
  {
    id: 47,
    category: "Noivos",
    name: "Noiva com as Unhas Feitas Garantido!",
    price: 480,
    image: "",
    pix: "",
  },
  {
    id: 48,
    category: "Noivos",
    name: "Nos Ajude a Pagar o Casamento!",
    price: 0,
    image: "",
    pix: "",
  },
  {
    id: 49,
    category: "Noivos",
    name: "Compra do Primeiro Mês Garantida!",
    price: 889,
    image: "",
    pix: "",
  },
  //Noivo TI
  {
    id: 50,
    category: "Noivo",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 51,
    category: "Noivo",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 52,
    category: "Noivo",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 53,
    category: "Noivo",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 54,
    category: "Noivo",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  //Noiva Designer
  {
    id: 55,
    category: "Noiva",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 56,
    category: "Noiva",  
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 57,
    category: "Noiva",  
    name: "",
    price: 0,
    image: "",  
    pix: "",
    link: "",
  },  
  {
    id: 58,
    category: "Noiva",
    name: "",
    price: 0,
    image: "",  
    pix: "",
    link: "",
  },  
  {
    id: 59,
    category: "Noiva",
    name: "",
    price: 0,
    image: "",  
    pix: "",
    link: "",
  },
  //Eletro
  {
    id: 60,
    category: "Eletro",
    name: "Panela de Arroz Elétrica Mondial Bianca Rice NPE-05-5X 5 Xícaras 400W",
    price: 129.90,
    image: "assets/Panela.jpg",
    pix: "",
    link: "https://www.magazineluiza.com.br/panela-de-arroz-eletrica-mondial-bianca-rice-npe-05-5x-5-xicaras-400w/p/236681900/ep/pael/",
  },
  {
    id: 61,
    category: "Eletro",
    name: "Batedeira Mondial Preta 400W Prática B-44-B - 3 Velocidades",
    price: 85.41,
    image: "assets/Batedeira.jpg",
    pix: "",
    link: "https://www.magazineluiza.com.br/batedeira-mondial-preta-400w-pratica-b-44-b-3-velocidades/p/021289100/ep/btdc/",
  },
  {
    id: 62,
    category: "Eletro",
    name: "MONDIAL Chaleira Elétrica Pratic, Preto/Inox, 1200W, 110V - CE-06",
    price: 110.90,
    image: "assets/Chaleira.jpg",
    pix: "",
    link: "https://a.co/d/9fQv5qB",
  },
  { 
    id: 63,
    category: "Eletro",
    name: "MONDIAL Climatizador Flash Air, Branco/Preto, 80W, 110V - CL-03",
    price: 491,
    image: "assets/Climatizador.jpg",
    pix: "",
    link: "https://a.co/d/iwJXqLs",
  },
  //Cozinha
  {
    id: 64,
    category: "Utensilhos",
    name: "Conjunto De Panelas Sartin Champ 7 Peças Cerâmica Mimo Stylee",
    price: 399.90,  
    image: "assets/Panelas.jpg",
    pix: "",
    
  }
];
