
//Eletro
const gifts = [
  {
    id: 1,
    category: "Eletro",
    name: "Geladeira/Refrigerador Brastemp Frost Free Duplex Prata 463L BRM55FK",
    price: 3699,
    image: 'assets/Geladeira.jpg',
    pix: "PIX_CODIGO_AQUI",
    link: "https://www.magazineluiza.com.br/geladeira-refrigerador-brastemp-frost-free-duplex-prata-463l-brm55fk/p/238402400/ed/refr/?partner_id=64853&utm_source=pdp_desk&utm_medium=share"
  },
  {
    id: 2,
    category: "Eletro",
    name: "Micro-Ondas Electrolux Prata com Painel Integrado 31L (MI41S)",
    price: 749,
  image: "assets/Microondas.jpg",
    pix: "PIX_CODIGO_AQUI",
    link: "https://site.fastshop.com.br/micro-ondas-electrolux-prata-com-painel-integrado-31l--mi41s--exmi41s_prd/p?idsku=12601&utm_source=bing&utm_medium=cpc&utm_campaign=%5Bli%5D_lb_%5Bst%5D_comercial_%5Bch%5D_1p_%5Bpl%5D_bing_%5Bty%5D_shop&utm_term=&utm_placement=o&msclkid=8b66da23f62a1d0c1c1db348f52b5466"
  },
  {
    id: 3,
    category: "Eletro",
    name: "Fogão 4 bocas Electrolux Prata Efficient com Mesa de Vidro, Tripla Chama e VaporBake",
    price: 1699,
    image: "assets/Fogão.jpg",
    pix: "PIX_CODIGO_AQUI",
    link: "https://loja.electrolux.com.br/fogao-4-bocas-electrolux-prata-efficient-com-mesa-de-vidro-perfectcook-e-vaporbake--fe4gs-/p?idsku=310120614&msclkid=8715e428882110340e338d438b8d31dc&utm_source=bing&utm_medium=cpc&utm_campaign=%5BVitrio%5D%20PLA%20%7C%20USC%20%7C%20Top%20Produtos&utm_term=2333713430298929&utm_content=Top%20Produtos  "
  },
  {
    id: 4,
    category: "Eletro",
    name: "Samsung Lava e Seca Digital Inverter Ecobubble™ WD10M Branca 10.1kg 220V",
    price: 3299,
    image:"assets/Maquina.jpg",
    pix: "",
    link: "https://a.co/d/1HJRsDg",
  },
  {
    id: 5,
    category: "Eletro",
    name: "Smart TV QLED 4K Samsung 55'' Q60B",
    price: 1597,
    image: "assets/Tv.jpg",
    pix: "",
    link: "https://www.magazineluiza.com.br/smart-tv-43-philips-full-hd-dled-43pfg6918-78-60hz-google-tv-quad-core-google-assistente-3-hdm/p/240247300/et/elit/?partner_id=64853&utm_source=pdp_desk&utm_medium=share"
  },
  {
    id: 6,
    category: "Eletro",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 7,
    category: "Eletro",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 8,
    category: "Eletro",
    name: "", 
    price: 0,
    image: "",
    pix: "",
    link: "",
  } ,
  { 
    id: 9,
    category: "Eletro",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",

  },
  {
    id: 10,
    category: "Eletro",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  } ,
  {
    id: 11,
    category: "Eletro",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 12,
    category: "Eletro",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 13,
    category: "Eletro",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  // Utensilhos
  {
  id: 14,
  category: "Utensilhos",
  name: "", 
  price: 0,
  image: "",
  pix: "",
  link: "",
  } ,
  {
    id: 15,
    category: "Utensilhos",
    name: "", 
    price: 0,
    image: "",
    pix: "",
    link: "",
  } ,
  {
    id: 16,
    category: "Utensilhos",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 17,
    category: "Utensilhos",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 18,
    category: "Utensilhos",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 19,
    category: "Utensilhos",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  //Banheiro
  {
    id: 20,
    category: "Banheiro",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  }, 
  {
    id: 21,
    category: "Banheiro",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 22,
    category: "Banheiro",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {    
    id: 23,
    category: "Banheiro",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  //Sala de Estar
  {
    id: 24,
    category: "SalaEstar",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 25,
    category: "SalaEstar",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 26,
    category: "SalaEstar",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 27,
    category: "SalaEstar",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 28,
    category: "SalaEstar",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 29,
    category: "SalaEstar",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  //Vale Presente
  {
    id: 30,
    category: "Vale",
    name: "Vale Presente R$ 200,00",
    price: 200,
    image: "",
    pix: "",

  },
  {
    id: 31,
    category: "Vale",
    name: "Vale Presente R$ 500,00",
    price: 500,
    image: "",
    pix: "",

  }, 
  {
    id: 32,
    category: "Vale",
    name: "Vale Presente R$ 1.000,00",
    price: 1000,
    image: "",
    pix: "",
  },
  {
    id: 33,
    category: "Vale",
    name: "Vale Presente R$ 1.500,00",
    price: 1500,
    image: "",
    pix: "",
  },
  {
    id: 34,
    category: "Vale",
    name: "Vale Presente R$ 2.000,00",
    price: 2000,
    image: "",
    pix: "",
  },
  {
    id: 35,
    category: "Vale",
    name: "Vale Presente R$ 2.500,00",
    price: 2500,
    image: "",
    pix: "",
  },
  {
    id: 36,
    category: "Vale",
    name: "Vale Presente R$ 3.000,00",
    price: 3000,
    image: "",
    pix: "",
  },
  //Quarto
  {
    id: 37,
    category: "Quarto",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 38,
    category: "Quarto",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 39,
    category: "Quarto",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {    id: 40,
    category: "Quarto",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 41,
    category: "Quarto",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 42,
    category: "Quarto",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 43,
    category: "Quarto",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  //Vida Noivos
  {
    id: 44,
    category: "Noivos",
    name: "Nos Ajude a Pagar a Lua de Mel!",
    price: 459,
    image: "",  
    pix: "",
  },
  {
    id: 45,
    category: "Noivos",
    name: "Nos Ajude a Pagar os Boletos (São muitos)",
    price: 250,
    image: "",
    pix: "",
  },
  {
    id: 46,
    category: "Noivos",
    name: "Noivo com o Cabelo Cortado Garantido!",
    price: 120,
    image: "",
    pix: "",
  },
  {
    id: 47,
    category: "Noivos",
    name: "Noiva com as Unhas Feitas Garantido!",
    price: 480,
    image: "",
    pix: "",
  },
  {
    id: 48,
    category: "Noivos",
    name: "Nos Ajude a Pagar o Casamento!",
    price: 0,
    image: "",
    pix: "",
  },
  {
    id: 49,
    category: "Noivos",
    name: "Compra do Primeiro Mês Garantida!",
    price: 889,
    image: "",
    pix: "",
  },
  //Noivo TI
  {
    id: 50,
    category: "Noivo",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 51,
    category: "Noivo",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 52,
    category: "Noivo",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 53,
    category: "Noivo",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 54,
    category: "Noivo",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  //Noiva Designer
  {
    id: 55,
    category: "Noiva",
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 56,
    category: "Noiva",  
    name: "",
    price: 0,
    image: "",
    pix: "",
    link: "",
  },
  {
    id: 57,
    category: "Noiva",  
    name: "",
    price: 0,
    image: "",  
    pix: "",
    link: "",
  },  
  {
    id: 58,
    category: "Noiva",
    name: "",
    price: 0,
    image: "",  
    pix: "",
    link: "",
  },  
  {
    id: 59,
    category: "Noiva",
    name: "",
    price: 0,
    image: "",  
    pix: "",
    link: "",
  },
  //Por enquanto chega
];
